AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket with a specific name

Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket
