AWSTemplateFormatVersion: '2010-09-09'
Description: Create an S3 bucket using a parameter.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: Name of the created bucket
    Value: !Ref S3Bucket
