AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 instance without SSH key pair

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-0cbe2951c50b70a48  # Amazon Linux 2 in eu-north-1 (replace if needed)
      Tags:
        - Key: Name
          Value: EC2WithoutKeyPair

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref EC2Instance
